import os

about_replacements = {
    "Triết lý Quản trị & Phát triển Tổ chức": "Management Philosophy & Organizational Development",
    "INVAMAX được hình thành từ thực tế vận hành trong các doanh nghiệp sản xuất FDI, kết hợp tư duy Lean, triết lý thuận tự nhiên và mô hình phát triển con người để xây những tổ chức hiệu quả và bền vững hơn.": "INVAMAX was formed from the practical operations of FDI manufacturing enterprises, combining Lean thinking, natural philosophy, and human development models to build more efficient and sustainable organizations.",
    "VỀ INVAMAX": "ABOUT INVAMAX",
    "Xây một môi trường vận hành nơi hệ thống và con người cùng phát triển": "Building an operating environment where both system and people thrive",
    "INVAMAX được hình thành từ thực tế quản lý và vận hành trong các doanh nghiệp sản xuất FDI — nơi năng suất, chất lượng, chi phí và kỷ luật vận hành luôn phải được duy trì ở mức cao.": "INVAMAX was forged in the practical management and operations of FDI manufacturing enterprises — where productivity, quality, cost, and operational discipline must constantly be maintained at high levels.",
    "Từ nền tảng thực tế đó, INVAMAX kết hợp phương pháp quản trị sản xuất Lean với một triết lý quản trị lấy con người và dòng vận hành thực tế làm trung tâm.": "From that practical foundation, INVAMAX combines Lean manufacturing management methods with a management philosophy centered on people and real operational flows.",
    "Một hệ thống tốt không bắt con người phải cố gắng nhiều hơn. Nó giúp công việc diễn ra tự nhiên hơn, ít áp lực hơn và tạo ra kết quả tốt hơn.": "A good system doesn't force people to try harder. It helps work flow more naturally, with less stress, yielding better results.",
    "01 &mdash; NỀN TẢNG THỰC TẾ": "01 &mdash; PRACTICAL FOUNDATION",
    "Từ thực tế nhà máy": "From the Factory Floor",
    "Không bắt đầu từ lý thuyết quản trị": "Not Starting from Management Theory",
    "INVAMAX được phát triển từ những vấn đề thực sự xảy ra trong nhà máy: áp lực sản lượng, chất lượng, giao hàng, chi phí, phối hợp giữa các bộ phận và năng lực của đội ngũ quản lý.": "INVAMAX was developed from real problems that occur in the factory: pressures on output, quality, delivery, cost, cross-departmental coordination, and management team capabilities.",
    "Thực tế đó tạo nên một nguyên tắc rất rõ:": "This reality shaped a very clear principle:",
    "Không thiết kế hệ thống từ những gì 'nên có'.<br>Thiết kế từ cách công việc thực sự diễn ra.": "Do not design systems from what 'should be'.<br>Design from how work actually happens.",
    "Lean cung cấp cho INVAMAX tư duy về dòng chảy, lãng phí, tiêu chuẩn và cải tiến liên tục.": "Lean provides INVAMAX with the mindset of flow, waste elimination, standards, and continuous improvement.",
    "Nhưng mục tiêu cuối cùng không phải là 'làm Lean'.": "But the ultimate goal is not just 'doing Lean'.",
    "Mục tiêu là tạo ra một môi trường vận hành đơn giản hơn, ổn định hơn và hiệu quả hơn.": "The goal is to create a simpler, more stable, and more efficient operating environment.",
    "02 &mdash; TRIẾT LÝ VẬN HÀNH": "02 &mdash; OPERATING PHILOSOPHY",
    "Thuận tự nhiên": "In Harmony with Nature",
    "Hiệu quả cao không đồng nghĩa với áp lực cao": "High Efficiency Does Not Mean High Stress",
    "Con người có giới hạn về thời gian, sự chú ý và năng lượng.": "Humans have limits in time, attention, and energy.",
    "Một tổ chức phải liên tục dựa vào thúc ép, theo sát và xử lý khẩn cấp để đạt kết quả là một tổ chức chưa được thiết kế tốt.": "An organization that constantly relies on pushing, micromanagement, and firefighting to achieve results is an organization not well-designed.",
    "INVAMAX theo đuổi triết lý thuận tự nhiên: thiết kế công việc và hệ thống sao cho những điều đúng trở nên dễ thực hiện hơn.": "INVAMAX pursues a philosophy of natural flow: designing work and systems so that doing the right thing becomes easier.",
    "Công việc có dòng chảy rõ ràng.": "Work has a clear flow.",
    "Trách nhiệm phù hợp với quyền hạn.": "Responsibilities match authority.",
    "Thông tin đến đúng người, đúng thời điểm.": "Information reaches the right people at the right time.",
    "Vấn đề được nhìn thấy sớm.": "Problems are identified early.",
    "Người quản lý không phải kiểm soát mọi việc.": "Managers don't have to control everything.",
    "Nhân viên có khả năng chủ động xử lý công việc.": "Employees have the ability to proactively handle tasks.",
    "Mục tiêu không phải làm cho con người chạy nhanh hơn.<br>Mục tiêu là loại bỏ những thứ khiến họ phải chạy.": "The goal is not to make people run faster.<br>The goal is to eliminate what makes them have to run.",
    "03 &mdash; CON NGƯỜI": "03 &mdash; PEOPLE",
    "Con người không chỉ là nguồn lực": "People are Not Just Resources",
    "Công việc phải là môi trường để con người trưởng thành": "Work Must be an Environment for Human Growth",
    "INVAMAX tin rằng doanh nghiệp không chỉ là nơi sử dụng năng lực của con người.": "INVAMAX believes that a business is not just a place to utilize human capabilities.",
    "Doanh nghiệp cũng phải là nơi năng lực đó được hình thành và phát triển.": "A business must also be a place where those capabilities are formed and developed.",
    "HỌC HỎI": "LEARNING",
    "LÀM CHỦ CÔNG VIỆC": "MASTERING WORK",
    "TẠO GIÁ TRỊ": "CREATING VALUE",
    "NHẬN LẠI GIÁ TRỊ": "RECEIVING VALUE",
    "TIẾP TỤC PHÁT TRIỂN": "CONTINUING TO DEVELOP",
    "Giá trị được trao đổi không chỉ là tiền lương.": "The value exchanged is not just a salary.",
    "Đó còn là kiến thức, kỹ năng, kinh nghiệm, cơ hội, trách nhiệm và sự trưởng thành.": "It is also knowledge, skills, experience, opportunities, responsibility, and personal growth.",
    "Khi cá nhân phát triển cùng với tổ chức, mối quan hệ giữa doanh nghiệp và người lao động không chỉ dừng lại ở việc trao đổi sức lao động.": "When individuals develop alongside the organization, the relationship between the business and employees goes beyond exchanging labor.",
    "Nó trở thành quá trình cùng nhau tạo ra và trao đổi giá trị.": "It becomes a process of co-creating and exchanging value.",
    "KIẾN THỨC &nbsp;&middot;&nbsp; KỸ NĂNG &nbsp;&middot;&nbsp; KINH NGHIỆM &nbsp;&middot;&nbsp; CƠ HỘI &nbsp;&middot;&nbsp; TRÁCH NHIỆM &nbsp;&middot;&nbsp; SỰ TRƯỞNG THÀNH": "KNOWLEDGE &nbsp;&middot;&nbsp; SKILLS &nbsp;&middot;&nbsp; EXPERIENCE &nbsp;&middot;&nbsp; OPPORTUNITIES &nbsp;&middot;&nbsp; RESPONSIBILITY &nbsp;&middot;&nbsp; GROWTH",
    "04 &mdash; MÔ HÌNH QUẢN LÝ": "04 &mdash; MANAGEMENT MODEL",
    "Doanh nghiệp trong doanh nghiệp": "Business Within a Business",
    "Mỗi người quản lý là người chủ của một đơn vị tạo giá trị": "Every Manager is the Owner of a Value-Creating Unit",
    "INVAMAX hướng tới một mô hình trong đó người quản lý không chỉ là người nhận chỉ đạo và phân công công việc cho cấp dưới.": "INVAMAX aims for a model where managers are not just receiving directives and assigning work to subordinates.",
    "Mỗi người quản lý được nhìn nhận như người chủ của một doanh nghiệp nhỏ bên trong doanh nghiệp lớn.": "Each manager is seen as the owner of a small business inside the larger enterprise.",
    "MỤC TIÊU": "OBJECTIVES",
    "Hiểu rõ đơn vị phải tạo ra kết quả gì.": "Clearly understand what results the unit must deliver.",
    "ĐỘI NGŨ": "TEAM",
    "Xây dựng và phát triển những con người do mình phụ trách.": "Build and develop the people under their charge.",
    "NGUỒN LỰC": "RESOURCES",
    "Quản lý thời gian, con người, thiết bị và nguồn lực được giao.": "Manage time, people, equipment, and assigned resources.",
    "QUYỀN CHỦ ĐỘNG": "AUTONOMY",
    "Có không gian ra quyết định trong phạm vi trách nhiệm.": "Have decision-making space within their scope of responsibility.",
    "TRÁCH NHIỆM": "RESPONSIBILITY",
    "Chịu trách nhiệm về kết quả của toàn bộ đơn vị.": "Take responsibility for the results of the entire unit.",
    "KẾT QUẢ": "RESULTS",
    "GIÁ TRỊ CHO TOÀN HỆ THỐNG": "VALUE FOR THE WHOLE SYSTEM",
    "Tự chủ không có nghĩa là hoạt động riêng lẻ. Tự chủ nghĩa là biết mình phải tạo ra giá trị gì cho toàn hệ thống.": "Autonomy doesn't mean operating in isolation. Autonomy means knowing what value to create for the whole system.",
    "Mỗi đơn vị vì vậy vừa có khả năng tự chủ, vừa phải kết nối và trao đổi giá trị với các đơn vị khác.": "Therefore, each unit is both autonomous and connected, exchanging value with other units.",
    "05 &mdash; ĐỊNH HƯỚNG": "05 &mdash; ORIENTATION",
    "Điều INVAMAX muốn xây dựng": "What INVAMAX Wants to Build",
    "Một cách vận hành tốt hơn cho nhà máy &mdash; và một môi trường tốt hơn cho con người": "A Better Operating Way for the Factory &mdash; and a Better Environment for People",
    "INVAMAX không hướng tới việc tạo thêm một phương pháp quản trị mới để doanh nghiệp phải học.": "INVAMAX does not aim to create yet another new management method for businesses to learn.",
    "Điều chúng tôi muốn xây là một cách tiếp cận kết hợp những gì đã được kiểm chứng trong thực tế sản xuất với một cách nhìn nhân bản hơn về tổ chức và con người.": "What we want to build is an approach combining what's proven in manufacturing practice with a more humanistic view of organizations and people.",
    "KỶ LUẬT VẬN HÀNH FDI": "FDI OPERATIONAL DISCIPLINE",
    "TƯ DUY LEAN": "LEAN THINKING",
    "TRIẾT LÝ THUẬN TỰ NHIÊN": "NATURAL PHILOSOPHY",
    "SỰ PHÁT TRIỂN &amp; TỰ CHỦ CỦA CON NGƯỜI": "HUMAN DEVELOPMENT &amp; AUTONOMY",
    "MỘT TỔ CHỨC TỐT HƠN": "A BETTER ORGANIZATION",
    "HIỆU QUẢ HƠN": "MORE EFFICIENT",
    "ÍT PHỤ THUỘC HƠN": "LESS DEPENDENT",
    "ÍT ÁP LỰC KHÔNG CẦN THIẾT HƠN": "LESS UNNECESSARY STRESS",
    "CÓ KHẢ NĂNG TỰ PHÁT TRIỂN TỐT HƠN": "BETTER SELF-DEVELOPMENT CAPABILITY",
    "Một doanh nghiệp mạnh không phải là nơi một vài người giỏi phải gánh cả hệ thống. Đó là nơi hệ thống giúp nhiều người có thể trở nên giỏi hơn.": "A strong business is not one where a few top performers carry the entire system. It is one where the system helps many become better.",
    "Xây một nhà máy tốt hơn cũng là xây một môi trường tốt hơn cho con người": "Building a Better Factory is Also Building a Better Environment for People",
    "INVAMAX tiếp tục kiểm chứng và phát triển những tư tưởng này thông qua công việc thực tế tại các doanh nghiệp sản xuất.": "INVAMAX continues to validate and develop these ideas through practical work at manufacturing enterprises.",
    "Khám phá Solutions": "Explore Solutions"
}

fos_replacements = {
    "INVAMAX FOS™ là hệ điều hành quản trị nhà máy gồm 11 module, kết nối nền móng quản trị, vận hành sản xuất, tri thức, công cụ, cải tiến và duy trì thành một hệ thống thống nhất.": "INVAMAX FOS™ is a factory management operating system comprising 11 modules, connecting management foundation, production operations, knowledge, tools, improvement, and sustenance into a unified system.",
    "HỆ ĐIỀU HÀNH QUẢN TRỊ NHÀ MÁY": "FACTORY MANAGEMENT OPERATING SYSTEM",
    "Biến cách nhà máy vận hành thành một hệ thống thống nhất": "Transforming Factory Operations into a Unified System",
    "INVAMAX FOS&trade; (Factory Operating System) là hệ điều hành quản trị nhà máy do INVAMAX phát triển,": "INVAMAX FOS&trade; (Factory Operating System) is a factory management operating system developed by INVAMAX,",
    "kết nối các hoạt động quản trị, sản xuất, tri thức, công cụ và cải tiến thành một hệ thống vận hành xuyên suốt.": "connecting management, production, knowledge, tools, and improvement activities into a seamless operating system.",
    "Cấu trúc của INVAMAX FOS&trade;": "Structure of INVAMAX FOS&trade;",
    "INVAMAX FOS&trade; tổ chức các năng lực cốt lõi của nhà máy thành một kiến trúc vận hành chung gồm 4 nhóm và 11 module liên kết.": "INVAMAX FOS&trade; organizes the core capabilities of a factory into a common operating architecture consisting of 4 groups and 11 interconnected modules.",
    "Nền móng quản trị": "Management Foundation",
    "Định hướng cách hệ thống được tổ chức và điều hành.": "Directs how the system is organized and managed.",
    "Vận hành sản xuất": "Production Operations",
    "Chuyển mục tiêu thành hoạt động thực tế hằng ngày.": "Translates goals into actual daily activities.",
    "Tri thức & Công cụ": "Knowledge & Tools",
    "Giữ tri thức trong hệ thống và hỗ trợ vận hành bằng công cụ phù hợp.": "Retains knowledge in the system and supports operations with appropriate tools.",
    "Cải tiến & Duy trì": "Improvement & Sustenance",
    "Giúp hệ thống giải quyết vấn đề và tiếp tục trưởng thành.": "Helps the system solve problems and continue to mature.",
    "FOS không thay thế đội ngũ quản lý. FOS tạo ra hệ thống để đội ngũ quản lý có thể vận hành nhà máy nhất quán hơn.": "FOS doesn't replace the management team. FOS creates a system so the management team can operate the factory more consistently.",
    "Bản đồ 11 module INVAMAX FOS&trade;": "Map of the 11 Modules of INVAMAX FOS&trade;",
    "MỘT HỆ THỐNG &middot; 4 NHÓM NĂNG LỰC &middot; 11 MODULE LIÊN KẾT": "ONE SYSTEM &middot; 4 CAPABILITY GROUPS &middot; 11 INTERCONNECTED MODULES",
    "11 module được tổ chức thành 4 nhóm, nhưng hoạt động như một hệ thống thống nhất.": "11 modules are organized into 4 groups, but they operate as one unified system.",
    "Nhóm 1 &mdash; Nền móng quản trị": "Group 1 &mdash; Management Foundation",
    "Chiến lược & Cơ chế điều hành": "Strategy & Operating Mechanism",
    "Kết nối mục tiêu doanh nghiệp với cơ chế quản trị, trách nhiệm và hoạt động vận hành.": "Connects corporate goals with management mechanisms, responsibilities, and operational activities.",
    "Con người & Capabilities tổ chức": "People & Organizational Capabilities",
    "Thiết kế vai trò, năng lực và nguồn lực con người phù hợp với mô hình vận hành.": "Designs roles, capabilities, and human resources suitable for the operating model.",
    "Quy trình & Dòng chảy": "Process & Flow",
    "Thiết kế cách công việc, vật liệu và thông tin đi xuyên qua hệ thống.": "Designs how work, materials, and information flow through the system.",
    "Nhóm 2 &mdash; Vận hành sản xuất": "Group 2 &mdash; Production Operations",
    "Công việc Tiêu chuẩn": "Standardized Work",
    "Xác lập cách công việc cần được thực hiện để tạo sự ổn định và nhất quán.": "Establishes how work needs to be done to create stability and consistency.",
    "Capabilities & Cân bằng": "Capacity & Balancing",
    "Cân đối nhu cầu, năng lực, con người, máy móc và các nguồn lực cần thiết.": "Balances demand, capacity, people, machinery, and necessary resources.",
    "Điều hành Hằng ngày": "Daily Management",
    "Tạo nhịp quản trị để theo dõi hoạt động, phát hiện bất thường và xử lý vấn đề.": "Creates a management rhythm to track activities, detect abnormalities, and handle problems.",
    "Chất lượng tại Nguồn": "Quality at the Source",
    "Đưa kiểm soát chất lượng vào trong chính quá trình tạo ra sản phẩm.": "Embeds quality control directly into the product creation process.",
    "Nhóm 3 &mdash; Tri thức & Công cụ": "Group 3 &mdash; Knowledge & Tools",
    "Quản trị Tri thức": "Knowledge Management",
    "Biến kiến thức và kinh nghiệm thành tài sản của tổ chức thay vì chỉ nằm trong cá nhân.": "Turns knowledge and experience into organizational assets rather than residing only in individuals.",
    "Công cụ Số": "Digital Tools",
    "Sử dụng công cụ số để hỗ trợ thông tin, dòng công việc, dữ liệu và hoạt động quản trị.": "Uses digital tools to support information, workflows, data, and management activities.",
    "Nhóm 4 &mdash; Cải tiến & Duy trì": "Group 4 &mdash; Improvement & Sustenance",
    "Giải quyết Vấn đề & Cải tiến": "Problem Solving & Kaizen",
    "Tạo cơ chế để bất thường được phát hiện, nguyên nhân được xử lý và cải tiến có hệ thống.": "Creates mechanisms for abnormalities to be detected, root causes addressed, and systematic improvement.",
    "Duy trì & Trưởng thành": "Sustain & Mature",
    "Giữ những thay đổi đã tạo ra và tiếp tục nâng cấp mức độ trưởng thành của hệ thống.": "Maintains the changes made and continues to elevate the system's maturity level.",
    "Giá trị của INVAMAX FOS&trade; nằm ở đâu?": "Where Does the Value of INVAMAX FOS&trade; Lie?",
    "Một kiến trúc vận hành thống nhất": "A Unified Operating Architecture",
    "Chiến lược, con người, quy trình, dữ liệu và cải tiến hoạt động trong cùng một logic.": "Strategy, people, process, data, and improvement operate within the same logic.",
    "Kết nối đầu-cuối thay vì tối ưu cục bộ": "End-to-End Connection Instead of Local Optimization",
    "Các phòng ban không chỉ tối ưu công việc riêng mà cùng phục vụ dòng vận hành chung.": "Departments do not just optimize their own tasks but serve the common operational flow together.",
    "Giảm phụ thuộc vào cách làm cá nhân": "Reduced Reliance on Individual Methods",
    "Cách vận hành được đưa vào hệ thống, tiêu chuẩn và cơ chế quản trị.": "Operating methods are built into the system, standards, and management mechanisms.",
    "Chuẩn hóa nhưng vẫn linh hoạt": "Standardized Yet Flexible",
    "FOS tạo ra một kiến trúc chung nhưng có thể điều chỉnh theo đặc điểm từng nhà máy.": "FOS creates a common architecture but can be adjusted to the specific characteristics of each factory.",
    "Tạo nền cho Lean, Digital & AI": "Laying the Groundwork for Lean, Digital & AI",
    "Cải tiến và công nghệ được đưa vào đúng vị trí của hệ thống thay vì triển khai rời rạc.": "Improvement and technology are placed in the right systemic positions rather than implemented disjointedly.",
    "FOS là lớp hệ thống đứng giữa Mô hình Vận hành Mục tiêu và hoạt động thực tế hằng ngày của nhà máy.": "FOS is the system layer sitting between the Target Operating Model and the actual daily operations of the factory.",
    "Nhà máy của bạn đang được vận hành bằng một hệ thống &mdash; hay bằng kinh nghiệm của những người đang ở đó?": "Is Your Factory Being Run by a System &mdash; or by the Experience of the People There?",
    "INVAMAX FOS&trade; giúp kết nối các hoạt động quản trị và vận hành rời rạc thành một hệ thống có cấu trúc, xuyên suốt và có khả năng tiếp tục phát triển.": "INVAMAX FOS&trade; helps connect disjointed management and operational activities into a structured, seamless, and continuously developing system.",
    "Tìm hiểu Operating Model Transformation": "Explore Operating Model Transformation",
    "Đối tác điều hành & Chuyển đổi mô hình vận hành nhà máy": "Operating Partner & Factory Operating Model Transformation",
    "Kết nối với chúng tôi": "Connect with us"
}


def process_file(file_path, replacements):
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    for vi, en in replacements.items():
        content = content.replace(vi, en)

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)

process_file('about.html', about_replacements)
process_file('fos.html', fos_replacements)
print("Translation applied.")
